# What Is DAX, and Why Is It Useful?
## Preprocess data
---

In [227]:
# Import modules
import pandas as pd
pd.set_option('display.max_columns', None) 
import os

In [228]:
# Define directories
rDir = "data"
wDir = "outputs"
happinessData = os.path.join(rDir, "world-happiness-index")
demographicsData = os.path.join(rDir, "world-demographics/WPP2022_Demographic_Indicators_Medium.csv")

### Happiness Data

In [229]:
# Read happiness data
df_list = []
for file in os.listdir(happinessData):
    year = file.split('.')[0]
    print(f"Reading year: {year}")
    df = pd.read_csv(os.path.join(happinessData, file))
    df['Year'] = year
    df_list.append(df)

df_happiness_idx = pd.concat(df_list)
df_happiness_idx.head()

Reading year: 2015
Reading year: 2016
Reading year: 2017
Reading year: 2018
Reading year: 2019
Reading year: 2020
Reading year: 2021
Reading year: 2022

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year,Lower Confidence Interval,Upper Confidence Interval,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Health..Life.Expectancy.,Trust..Government.Corruption.,Dystopia.Residual,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Perceptions of corruption,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,RANK,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita
0,Switzerland,Western Europe,1.0,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Iceland,Western Europe,2.0,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Denmark,Western Europe,3.0,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Norway,Western Europe,4.0,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Canada,North America,5.0,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [230]:
list(df_happiness_idx.columns)

['Country',
 'Region',
 'Happiness Rank',
 'Happiness Score',
 'Standard Error',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Trust (Government Corruption)',
 'Generosity',
 'Dystopia Residual',
 'Year',
 'Lower Confidence Interval',
 'Upper Confidence Interval',
 'Happiness.Rank',
 'Happiness.Score',
 'Whisker.high',
 'Whisker.low',
 'Economy..GDP.per.Capita.',
 'Health..Life.Expectancy.',
 'Trust..Government.Corruption.',
 'Dystopia.Residual',
 'Overall rank',
 'Country or region',
 'Score',
 'GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Perceptions of corruption',
 'Country name',
 'Regional indicator',
 'Ladder score',
 'Standard error of ladder score',
 'upperwhisker',
 'lowerwhisker',
 'Logged GDP per capita',
 'Ladder score in Dystopia',
 'Explained by: Log GDP per capita',
 'Explained by: Social support',
 'Explained by: Healthy life expectancy',
 'Explained by: Freedom to make life choices',
 'Explained by: Generosity',
 'Explained by: Perceptions of corruption',
 'Dystopia + residual',
 'RANK',
 'Happiness score',
 'Whisker-high',
 'Whisker-low',
 'Dystopia (1.83) + residual',
 'Explained by: GDP per capita']

In [231]:
happiness_idx_columns = ['Country',
                         'Region',
                         'Year',
                         'Happiness Rank',
                         'Happiness Score',
                         'Standard Error',
                         'Economy (GDP per Capita)',
                         'Family',
                         'Health (Life Expectancy)',
                         'Freedom',
                         'Trust (Government Corruption)',
                         'Generosity',
                         'Dystopia Residual']

df_happiness_idx = df_happiness_idx[happiness_idx_columns]

In [232]:
df_happiness_idx.dropna(subset = ['Country'], inplace=True)
df_happiness_countries = list(df_happiness_idx['Country'].unique())
df_happiness_countries.sort()
df_happiness_countries

['Afghanistan',
 'Albania',
 'Algeria',
 'Angola',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Azerbaijan*',
 'Bahrain',
 'Bangladesh',
 'Belarus',
 'Belarus*',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Botswana*',
 'Brazil',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Central African Republic',
 'Chad',
 'Chad*',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Comoros*',
 'Congo',
 'Congo (Brazzaville)',
 'Congo (Kinshasa)',
 'Costa Rica',
 'Croatia',
 'Cyprus',
 'Czech Republic',
 'Czechia',
 'Denmark',
 'Djibouti',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Estonia',
 'Eswatini, Kingdom of*',
 'Ethiopia',
 'Finland',
 'France',
 'Gabon',
 'Gambia*',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guatemala',
 'Guatemala*',
 'Guinea',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hong Kong S.A.R. of China',
 'Hong Kong S.A.R., China',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kosovo',
 'Kuwait',
 'Kuwait*',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Lesotho*',
 'Liberia',
 'Liberia*',
 'Libya',
 'Libya*',
 'Lithuania',
 'Luxembourg',
 'Luxembourg*',
 'Macedonia',
 'Madagascar',
 'Madagascar*',
 'Malawi',
 'Malaysia',
 'Mali',
 'Malta',
 'Mauritania',
 'Mauritania*',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Niger*',
 'Nigeria',
 'North Cyprus',
 'North Cyprus*',
 'North Macedonia',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestinian Territories',
 'Palestinian Territories*',
 'Panama',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Rwanda*',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Somalia',
 'Somaliland Region',
 'Somaliland region',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Taiwan Province of China',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turkmenistan*',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Yemen*',
 'Zambia',
 'Zimbabwe',
 'xx']

In [233]:
df_happiness_countries = [country for country in df_happiness_countries if '*' not in country and 'xx' not in country]
df_happiness_idx = df_happiness_idx[df_happiness_idx['Country'].isin(df_happiness_countries)].reset_index(drop=True)
df_happiness_idx.shape

(595, 13)

In [234]:
df_happiness_idx.describe()

,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
count,315.000000,315.000000,158.000000,315.000000,470.000000,315.000000,470.000000,315.000000,470.000000,315.000000
mean,79.238095,5.378949,0.047885,0.899837,0.990347,0.594054,0.402828,0.140532,0.242241,2.212032
std,45.538922,1.141531,0.017146,0.410780,0.318707,0.240790,0.150356,0.115490,0.131543,0.558728
min,1.000000,2.839000,0.018480,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.328580
25%,40.000000,4.510000,0.037268,0.594900,0.793000,0.419645,0.297615,0.061315,0.152831,1.884135
50%,79.000000,5.286000,0.043940,0.973060,1.025665,0.640450,0.418347,0.106130,0.223140,2.211260
75%,118.500000,6.269000,0.052300,1.229000,1.228745,0.787640,0.516850,0.178610,0.315824,2.563470
max,158.000000,7.587000,0.136930,1.824270,1.610574,1.025250,0.669730,0.551910,0.838075,3.837720

### Demographics Data

In [235]:
df_demographics = pd.read_csv(demographicsData)
df_demographics.tail()

C:\Users\Pablo\AppData\Local\Temp\ipykernel_19524\1453149769.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_demographics = pd.read_csv(demographicsData)

,SortOrder,LocID,Notes,ISO3_code,ISO2_code,SDMX_code,LocTypeID,LocTypeName,ParentID,Location,VarID,Variant,Time,TPopulation1Jan,TPopulation1July,TPopulationMale1July,TPopulationFemale1July,PopDensity,PopSexRatio,MedianAgePop,NatChange,NatChangeRT,PopChange,PopGrowthRate,DoublingTime,Births,Births1519,CBR,TFR,NRR,MAC,SRB,Deaths,DeathsMale,DeathsFemale,CDR,LEx,LExMale,LExFemale,LE15,LE15Male,LE15Female,LE65,LE65Male,LE65Female,LE80,LE80Male,LE80Female,InfantDeaths,IMR,LBsurvivingAge1,Under5Deaths,Q5,Q0040,Q0040Male,Q0040Female,Q0060,Q0060Male,Q0060Female,Q1550,Q1550Male,Q1550Female,Q1560,Q1560Male,Q1560Female,NetMigrations,CNMR
43467,290,876,2.0,WLF,WF,876.0,4,Country/Area,957,Wallis and Futuna Islands,2,Medium,2097,10.063,10.036,4.994,5.042,71.6857,99.0480,50.0961,-0.037,-3.699,-0.054,-0.538,NaN,0.086,0.002,8.533,1.6965,0.8218,30.476,104.8,0.123,0.059,0.064,12.232,89.2802,88.7006,89.7993,74.6892,73.9610,75.3659,25.9523,25.1938,26.6564,13.7656,13.2265,14.2204,0.0,3.6722,0.086,0.0,4.2671,7.5238,5.2973,9.8410,25.5384,23.1199,28.0450,7.5105,6.3613,8.6783,21.0197,20.2116,21.8411,-0.01,-0.995
43468,290,876,2.0,WLF,WF,876.0,4,Country/Area,957,Wallis and Futuna Islands,2,Medium,2098,10.009,9.989,4.971,5.018,71.3500,99.0634,50.2617,-0.039,-3.905,-0.040,-0.400,NaN,0.085,0.002,8.516,1.6911,0.8193,30.491,104.8,0.124,0.060,0.064,12.421,89.4087,88.8012,89.9626,74.8108,74.0585,75.5184,26.0540,25.2769,26.7834,13.8367,13.2845,14.3120,0.0,3.6063,0.085,0.0,4.1903,7.3835,5.2259,9.6289,25.0627,22.7966,27.4133,7.3642,6.2703,8.4752,20.6236,19.9248,21.3338,-0.01,-1.000
43469,290,876,2.0,WLF,WF,876.0,4,Country/Area,957,Wallis and Futuna Islands,2,Medium,2099,9.969,9.940,4.947,4.992,71.0000,99.0986,50.4049,-0.041,-4.102,-0.058,-0.584,NaN,0.085,0.002,8.529,1.6924,0.8200,30.507,104.8,0.126,0.061,0.065,12.631,89.5113,88.9026,90.0724,74.9084,74.1569,75.6211,26.1357,25.3608,26.8689,13.8930,13.3432,14.3738,0.0,3.5572,0.085,0.0,4.1333,7.2777,5.1545,9.4875,24.6911,22.4732,26.9919,7.2513,6.1793,8.3398,20.3113,19.6379,20.9955,-0.01,-1.005
43470,290,876,2.0,WLF,WF,876.0,4,Country/Area,957,Wallis and Futuna Islands,2,Medium,2100,9.911,9.887,4.922,4.965,70.6250,99.1240,50.5031,-0.043,-4.325,-0.047,-0.475,NaN,0.084,0.002,8.512,1.6887,0.8183,30.522,104.8,0.127,0.062,0.065,12.837,89.6067,89.0048,90.1660,74.9994,74.2560,75.7089,26.2127,25.4454,26.9436,13.9470,13.4024,14.4294,0.0,3.5147,0.084,0.0,4.0840,7.1864,5.0831,9.3753,24.3648,22.1497,26.6620,7.1535,6.0883,8.2346,20.0363,19.3509,20.7325,-0.01,-1.011
43471,290,876,2.0,WLF,WF,876.0,4,Country/Area,957,Wallis and Futuna Islands,2,Medium,2101,9.864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [236]:
df_demographics = df_demographics[(df_demographics['LocTypeName'] == 'Country/Area') & (df_demographics['Time'].isin([2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]))].reset_index(drop = True)
df_demographics.rename(columns = {'Location': 'Country',
                                  'Time': 'Year'},
                                  inplace=True
                        )
df_demographics = df_demographics[['Country', 'Year', 'PopDensity', 'PopSexRatio', 'MedianAgePop', 'PopGrowthRate', 'Births', 'Deaths', 'DeathsMale', 'DeathsFemale', 'NetMigrations']]
df_demographics.head()

,Country,Year,PopDensity,PopSexRatio,MedianAgePop,PopGrowthRate,Births,Deaths,DeathsMale,DeathsFemale,NetMigrations
0,Burundi,2015,413.3776,98.3798,15.6299,1.109,448.194,92.775,49.285,43.490,-236.447
1,Burundi,2016,420.1668,98.4060,15.2445,2.141,432.480,89.609,46.858,42.751,-109.490
2,Burundi,2017,429.8880,98.4556,15.0911,2.431,426.555,86.959,45.663,41.296,-68.450
3,Burundi,2018,442.9084,98.5103,15.1473,3.521,424.108,87.635,46.196,41.439,68.145
4,Burundi,2019,457.6045,98.5573,15.3081,3.016,431.143,87.264,46.457,40.806,14.241

### Data Wrangling

We need to filter only the countries that are common to both datasets.

In [237]:
(df_demographics['Country'].nunique(), df_happiness_idx['Country'].nunique())

(237, 170)

In [238]:
countries_consolidated = [country for country in df_demographics['Country'].unique() if country in df_happiness_idx['Country'].unique()]
len(countries_consolidated)

142

In [239]:
df_demographics = df_demographics[df_demographics['Country'].isin(countries_consolidated)].reset_index(drop=True)
df_happiness_idx = df_happiness_idx[df_happiness_idx['Country'].isin(countries_consolidated)].reset_index(drop=True)

In [240]:
(df_demographics.shape, df_happiness_idx.shape)

((1136, 11), (512, 13))

We now need to create a numeric country key to use in our data model.

In [241]:
country_list = df_demographics['Country'].unique()
country_list.sort()
country_identifiers = list(range(1, len(country_list) + 1))

In [242]:
country_ids = dict(zip(country_list, country_identifiers))

In [243]:
df_countries = pd.DataFrame(country_ids.items(), columns = ['Country', 'Country_ID'])

In [244]:
df_happiness_idx['Country_ID'] = df_happiness_idx['Country'].map(country_ids)
df_demographics['Country_ID'] = df_demographics['Country'].map(country_ids)

In [245]:
regions = df_happiness_idx.drop_duplicates('Country_ID').set_index('Country_ID')['Region']
df_countries['Region'] = df_countries['Country_ID'].map(regions)

In [246]:
df_happiness_idx.drop(columns = ['Country', 'Region'], inplace=True)
df_demographics.drop(columns = ['Country'], inplace=True)

### Data Writing

In [247]:
df_countries.to_csv(os.path.join(wDir, 'countries.csv'), index=False)
df_happiness_idx.to_csv(os.path.join(wDir, 'happiness_index.csv'), index=False)
df_demographics.to_csv(os.path.join(wDir, 'demographics.csv'), index=False)